# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_check_args: --as-cran

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

bioc_required: yes
use_bioc: yes
r:
- release
- devel
addons:
  apt:
    packages:
    - tcl8.5-dev
    - tk8.5-dev